### ISSUE TITLE
Scratch embeds are showing 404

### ISSUE THREAD

**Issue by jacobischwartz** [Booligoosh/boolicode#5]
All the scratch embeds on this site are showing errors. See screenshot attached!

The problem might be that the Scratch projects are not publicly viewable. You might need to share them in Scratch. Try viewing the page in incognito mode on your browser to replicate the issue.

<img width="548" alt="screen shot 2016-05-01 at 9 56 59 am" src="https://cloud.githubusercontent.com/assets/1933982/14942450/18975c06-0f83-11e6-9a2b-54d87ad3dd63.png">

**Comment by Booligoosh** [comment]
Thanks for noticing. I have actually unshared them so this website is redundant now.
